export const defaultA2uiTheme = {
  components: {
    AudioPlayer: {},
    Button: {
      'typography-f-sf': true,
      'typography-fs-n': true,
      'typography-w-500': true,
      'typography-td-none': true,
      'layout-pt-2': true,
      'layout-pb-2': true,
      'layout-pl-4': true,
      'layout-pr-4': true,
      'border-br-12': true,
      'border-bw-0': true,
      'border-bs-s': true,
      'color-bgc-p30': true,
      'color-c-n100': true,
      'behavior-ho-70': true,
    },
    Card: {
      'border-br-9': true,
      'border-bw-1': true,
      'border-bs-s': true,
      'color-bc-n80': true,
      'layout-p-4': true,
      'color-bgc-n100': true,
    },
    CheckBox: {
      container: {},
      label: {},
      element: {},
    },
    Column: {
      'layout-g-2': true,
      'layout-w-100': true,
    },
    DateTimeInput: {
      container: {},
      label: {},
      element: {},
    },
    Divider: {},
    Icon: {},
    Image: {
      all: {},
      avatar: {},
      header: {},
      icon: {},
      largeFeature: {},
      mediumFeature: {},
      smallFeature: {},
    },
    List: {},
    Modal: {
      backdrop: {},
      element: {},
    },
    MultipleChoice: {
      container: {},
      label: {},
      element: {},
    },
    Row: {},
    Slider: {
      container: {},
      label: {},
      element: {},
    },
    Tabs: {
      container: {},
      controls: {
        all: {},
        selected: {},
      },
      element: {},
    },
    Text: {
      all: {
        'layout-w-100': true,
        'typography-f-s': true,
        'typography-fs-n': true,
        'typography-w-400': true,
        'typography-sz-bm': true,
        'color-c-n10': true,
      },
      h1: {
        'typography-f-sf': true,
        'typography-w-500': true,
        'typography-sz-hs': true,
        'layout-m-0': true,
      },
      h2: {
        'typography-f-sf': true,
        'typography-w-500': true,
        'typography-sz-tl': true,
        'layout-m-0': true,
      },
      h3: {
        'typography-f-sf': true,
        'typography-w-500': true,
        'typography-sz-bl': true,
        'layout-m-0': true,
      },
      h4: {
        'typography-f-sf': true,
        'typography-w-500': true,
        'typography-sz-bl': true,
        'layout-m-0': true,
      },
      h5: {
        'typography-f-sf': true,
        'typography-w-500': true,
        'typography-sz-bm': true,
        'layout-m-0': true,
      },
      body: {},
      caption: {
        'typography-f-s': true,
        'typography-w-400': true,
        'typography-sz-bm': true,
        'opacity-o-70': true,
      },
    },
    TextField: {
      container: {},
      label: {},
      element: {},
    },
    Video: {},
  },
  elements: {
    a: {},
    audio: {},
    body: {},
    button: {},
    h1: {},
    h2: {},
    h3: {},
    h4: {},
    h5: {},
    iframe: {},
    input: {},
    p: {},
    pre: {},
    textarea: {},
    video: {},
  },
  markdown: {
    p: [],
    h1: [],
    h2: [],
    h3: [],
    h4: [],
    h5: [],
    ul: [],
    ol: [],
    li: [],
    a: [],
    strong: [],
    em: [],
  },
  additionalStyles: {
    Card: {
      background:
        'radial-gradient(circle at top left, rgba(6, 182, 212, 0.12), transparent 40%), radial-gradient(circle at bottom right, rgba(139, 92, 246, 0.12), transparent 40%), rgba(15, 23, 42, 0.65)',
    },
    Text: {
      h1: {
        color: 'transparent',
        background: 'linear-gradient(135deg, #818cf8 0%, #22d3ee 100%)',
        WebkitBackgroundClip: 'text',
        backgroundClip: 'text',
        WebkitTextFillColor: 'transparent',
      },
      h2: {
        color: 'transparent',
        background: 'linear-gradient(135deg, #a78bfa 0%, #60a5fa 100%)',
        WebkitBackgroundClip: 'text',
        backgroundClip: 'text',
        WebkitTextFillColor: 'transparent',
      },
      h3: {},
      h4: {},
      h5: {},
      body: {},
      caption: {},
    },
    Button: {
      background: 'linear-gradient(135deg, #6366f1 0%, #22d3ee 100%)',
      boxShadow: '0 6px 18px rgba(99, 102, 241, 0.25)',
    },
  },
}

