export const defaultA2uiTheme = {
  components: {
    AudioPlayer: {},
    Button: {
      'typography-f-sf': true,
      'typography-fs-n': true,
      'typography-w-500': true,
      'typography-td-none': true,
      'layout-pt-2': true,
      'layout-pb-2': true,
      'layout-pl-4': true,
      'layout-pr-4': true,
      'border-br-12': true,
      'border-bw-0': true,
      'border-bs-s': true,
      'color-bgc-n30': true,
      'color-c-n0': true,
      'behavior-ho-70': true,
    },
    Card: {
      'border-br-12': true,
      'border-bw-1': true,
      'border-bs-s': true,
      'color-bc-n90': true,
      'layout-p-6': true,
      'color-bgc-n100': true,
    },
    CheckBox: {
      container: {},
      label: {},
      element: {},
    },
    Column: {
      'layout-g-4': true,
      'layout-w-100': true,
    },
    DateTimeInput: {
      container: {},
      label: {},
      element: {},
    },
    Divider: {},
    Icon: {},
    Image: {
      all: {},
      avatar: {},
      header: {},
      icon: {},
      largeFeature: {},
      mediumFeature: {},
      smallFeature: {},
    },
    List: {},
    Modal: {
      backdrop: {},
      element: {},
    },
    MultipleChoice: {
      container: {},
      label: {},
      element: {},
    },
    Row: {
      'layout-g-4': true,
    },
    Slider: {
      container: {},
      label: {},
      element: {},
    },
    Tabs: {
      container: {},
      controls: {
        all: {},
        selected: {},
      },
      element: {},
    },
    Text: {
      all: {
        'layout-w-100': true,
        'typography-f-s': true,
        'typography-fs-n': true,
        'typography-w-400': true,
        'typography-sz-bm': true,
        'color-c-n5': true,
      },
      h1: {
        'typography-f-sf': true,
        'typography-w-500': true,
        'typography-sz-hs': true,
        'layout-m-0': true,
      },
      h2: {
        'typography-f-sf': true,
        'typography-w-500': true,
        'typography-sz-tl': true,
        'layout-m-0': true,
      },
      h3: {
        'typography-f-sf': true,
        'typography-w-500': true,
        'typography-sz-bl': true,
        'layout-m-0': true,
        'layout-mt-0': true,
        'layout-mb-0': true,
      },
      h4: {
        'typography-f-sf': true,
        'typography-w-500': true,
        'typography-sz-bl': true,
        'layout-m-0': true,
      },
      h5: {
        'typography-f-sf': true,
        'typography-w-500': true,
        'typography-sz-bm': true,
        'layout-m-0': true,
      },
      body: {
        'layout-m-0': true,
      },
      caption: {
        'typography-f-s': true,
        'typography-w-400': true,
        'typography-sz-bm': true,
        'opacity-o-70': true,
        'layout-m-0': true,
      },
    },
    TextField: {
      container: {},
      label: {},
      element: {},
    },
    Video: {},
  },
  elements: {
    a: {},
    audio: {},
    body: {},
    button: {},
    h1: {
      margin: '0',
    },
    h2: {
      margin: '0',
    },
    h3: {
      margin: '0',
      marginTop: '0',
      marginBottom: '0',
    },
    h4: {
      margin: '0',
    },
    h5: {
      margin: '0',
    },
    iframe: {},
    input: {},
    p: {},
    pre: {},
    textarea: {},
    video: {},
  },
  markdown: {
    p: [],
    h1: [],
    h2: [],
    h3: [],
    h4: [],
    h5: [],
    ul: [],
    ol: [],
    li: [],
    a: [],
    strong: [],
    em: [],
  },
  additionalStyles: {
    Card: 'background: var(--n-100); box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1), 0 1px 2px rgba(0, 0, 0, 0.06);',
    Button: 'background: var(--n-30); box-shadow: 0 1px 2px rgba(0, 0, 0, 0.1);',
  },
}

